language: cpp
sudo: required
compiler:
  - clang
  - gcc
distro: trusty
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then bash .travis/install-sodium-trusty.sh; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sodium; fi
script:
  - cmake . && make && make check